import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import { AppLoader } from "./app-loader";
import "./globals.css";
import { Toaster } from "@/shared/ui/toaster"

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} antialiased h-screen bg-foreground text-background font-inter`}
			>
				<AppLoader>
					{children}
					<Toaster />
				</AppLoader>
			</body>
		</html>
	);
}
